name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.python.name }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
        python:
          - name: CPython 3.6
            tox: py36
            action: 3.6
          - name: CPython 3.7
            tox: py37
            action: 3.7
          - name: CPython 3.8
            tox: py38
            action: 3.8
          - name: CPython 3.9
            tox: py39
            action: 3.9
        include:
            os:
              - name: Windows
                runs-on: windows-latest
            python:
              - name: CPython 3.9
                tox: py39
                action: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python.name }}
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python.action }}.0-alpha - ${{ matrix.python.action }}.X'
          architecture: x64
      - uses: twisted/python-info-action@v1.0.1
      - name: Install Linux Qt5 dependencies
        if: matrix.os.matrix == 'linux'
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes libgl1
          # Required to stubtest QtMultimedia
          sudo apt-get install --yes libpulse-mainloop-glib0
      - name: Install
        run: |
          pip install --upgrade pip setuptools wheel
          pip install tox
      - name: Test
        run: |
          tox -v -e ${{ matrix.python.tox }}

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: This
        shell: python
        run: |
          import this
