name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - "*"
  schedule:
    # Daily at 06:14
    - cron: '14 6 * * *'

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
            matrix: linux
          - name: Windows
            runs-on: windows-latest
            matrix: windows
          - name: macOS
            runs-on: macos-latest
            matrix: macos
        python:
          - name: CPython 3.6
            tox: py36
            action: 3.6
          - name: CPython 3.7
            tox: py37
            action: 3.7
          - name: CPython 3.8
            tox: py38
            action: 3.8
          - name: CPython 3.9
            tox: py39
            action: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python.name }}
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python.action }}.0-alpha - ${{ matrix.python.action }}.X'
          architecture: x64
      - uses: twisted/python-info-action@v1.0.1
      - name: Install Linux Qt5 dependencies
        if: matrix.os.matrix == 'linux'
        run: |
          apt-get update --yes
          apt-get install --yes libgl1
      - name: Install
        run: |
          pip install --upgrade pip setuptools wheel
          pip install tox
      - name: Test
        run: |
          tox -v -e ${{ matrix.python.tox }}

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
      - check
    steps:
      - name: This
        shell: python
        run: |
          import this